Show better schema errors (#63)
This brings back `errReadDefinition` to tell users why their schema is failing.

Before:
```
Error: Invalid format: [(root): Must validate one and only one schema (oneOf) timeout: Invalid type. Expected: number, given: string (root): Must validate all the schemas (allOf)]
```

After:
```
(root): Must validate one and only one schema (oneOf)
timeout: Invalid type. Expected: number, given: string
image: image is required
(root): Must validate all the schemas (allOf)

For more information on the task definition format, see the docs:
https://docs.airplane.dev/deprecated/task-definition-reference
```

(We'll need to update the task defn link!)

The change to the schema is to pin the schema to a particular JSON schema draft, & also to put a restriction on additional properties.

Resolves AIR-3062.